### ISSUE TITLE
[BUG] Dangerous default timeout

### ISSUE THREAD

**Issue by Nuranto** [crowdsecurity/cs-magento-bouncer#21]
**Describe the bug**

**Preconditions**

- Magento 2 version: 2.4.6-p3
- CrowdSec_Bouncer module version: latest
- Environment (Developer or Production mode): production

**To Reproduce**

1. Simulate a crash from the crowdesc API server (just shut it down)

**Expected result**

No impact for visitors. No more bouncing.

**Actual result**
A clear and concise description of the actual result.

Site almost down, since every request is waiting the 120seconds timeout used by this module.

**Comment by julienloizelet** [comment]
Hi @Nuranto , thanks for your message.

The stream mode should avoid this kind of problem, or at least reduce the negative impact on the site.
In stream mode, LAPI CrowdSec is not called on each visit, but only when the cache is refreshed by a cron task.

In live mode, I agree that timeout management could be improved.

First of all, we could make the timeout value configurable.

Secondly, with `curl`, we use the timeout value as a[ `CURLOPT_TIMEOUT` option](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html) (i.e. the total time of a transfer operation). We do this to be consistent with the `http.timeout`  option of `file_get_contents`.
Perhaps, for curl at least, we could be more refined, as curl also has the [`CURLOPT_CONNECTTIMEOUT` option](https://curl.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html), which allows us to manage only the timeout for the connect phase.

I'll discuss this with the team to see what can be done.

Thanks again.

**Comment by julienloizelet** [comment]
Hi,

In the [2.1.0 release](https://github.com/crowdsecurity/cs-magento-bouncer/releases/tag/v2.1.0) we added 2 configurations for the timeout: https://github.com/crowdsecurity/cs-magento-bouncer/blob/v2.1.0/doc/USER_GUIDE.md#general-settings (Global timeout and, for curl only, connection timeout)

It doesn't solve the problem in Live mode, as bouncer will continue to try bouncing,  but it can reduce the impact.

To completely avoid the impact of an unreachable  LAPI, we recommend using Stream mode.

Thanks

**Comment by LaurenceJJones** [comment]
Issue has been open for sometime and a resolution appears to be done.

Please reopen issue if the solution does not appear to meet expectation.
